config/routes.rb
=begin

  @File Name                 : routes.rb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-05
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To redirect the pages throughout the application.

=end

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  #resources :pages

  # defining root path for the application
  #root :to => "pages#home"

  # post to page preview action
  post 'pages/preview'     => 'pages#preview', :as => :preview_pages

  match 'pages/blog/preview' => redirect("/blog/posts") if Gem.available?("mcms_blog")

  # match pages/**/preview to action preview of pages controller
  match 'pages/*path/preview' => 'pages#preview', :as => :preview_page,  :via => [:get, :put]

  # define route for namespace admin for different resources to have
  # path prefixed with "mcms"
  namespace :admin, :path => "mcms" do

    # matching pages/page_title OR id/find_child will be redirected to
    # find_child action for pages controller within namespace admin
    match 'pages/*path/find_child', :to => 'pages#find_child'

    # get edit path for parent and child(url prepended with parent) page both
    # and redirect to edit action
    get 'pages/*path/edit', :to => 'pages#edit'

    resources :layouts do

      collection do

        get 'find_and_use_layout'

      end

    end

    resources :pages do

      collection do

        get 'add_page_part'

      end

    end

  end # end namespace

  match '/:path' => "pages#show"

  match '*path', :to=> 'pages#show', :as => :show_page unless Gem.available?("mcms")

end

app/views/mcms_pages/admin/pages/_action.html.erb
<!--

  @File Name                 : admin/pages/_mcms_action.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-09
  @Date Modified             : 2012-06-14
  @Last Modification Details : 'mcms-' removed from css selectors
  @Purpose                   : Application level action for admin pages will be defined here.

-->


<div class="repos application-actions">

  <div class="top-bar">

    <h2>Quick tasks </h2>
    <%= link_to "Add a New Page", new_admin_page_path, :id => "page-new", :class =>"button new-repo" %>

  </div>

  <ul class="repo-list">

    <li class="public source">

      <a href="/" target="_blank">

        <span class="mini-icon"></span>
        <span class="owner">Switch to Website</span><span class="repo"></span>
        <span class="arrow"></span>
        
      </a>

    </li>

  </ul>

  <div class="bottom-bar">
  </div>

</div>

app/views/mcms_pages/admin/pages/_error_messages.html.erb
<!--

  @File Name                 : admin/pages/_error_messages.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-07-04
  @Date Modified             : 
  @Last Modification Details : 
  @Purpose                   : To display the form errors

-->

<!-- check for occurences of any errors --> 
<% if object.errors.any? %>

  <div class="error-explanation" id="error-explanation">
    
    <ul>

      <% unless defined?(include_object_name) and include_object_name %>
      
        <% object.errors.each do |key, value| %>
      
          <li><%= value %></li>
          
        <% end %>
          
      <% else %>
          
        <% object.errors.full_messages.each do |value| %>
          
          <li><%= value %></li>
          
        <% end %>
          
      <% end %>
          
    </ul>

  </div>

<% end %>

app/views/mcms_pages/admin/pages/_form.html.erb
<!--

  @File Name                 : admin/pages/_form.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-05
  @Date Modified             : 2012-06-15
  @Last Modification Details : Layout field changed from select box to hidden field
  @Purpose                   : To display the form to create and edit pages and page parts
                               using form helpers to renders the form fields using erb tag.

-->

<!-- displaying form for creating pages -->
<%= form_for [:admin, @page] do |f| %>

  <!-- render partial for error messages with some locals -->
  <%= render :partial => "mcms_pages/admin/pages/error_messages",
             :locals => {
               :object => f.object,
               :include_object_name => true
             } %>

  <div class="field">

    <!-- calling form helper method to render dropdown box -->
    <%= f.hidden_field :layout_id, :value => "#{@layout}" %>

  </div>
  <div class="field">

    <%= f.label :title, "Title of the Page:" %>
    <%= f.text_field :title, :title => "This will be the title of your page" %>

  </div>
  <div class='field'>

    <%= f.label :body, "Content of the Page:" %>

    <% if controller.action_name == 'new' or controller.action_name == 'create'%>

      <!-- rendering partial page part form -->
      <%= render 'mcms_pages/admin/pages/page_part_form', :f => f %>

    <% else %>

      <!-- rendering partial page part form -->
      <%= render 'mcms_pages/admin/pages/page_part_edit_form', :f => f %>

    <% end %>

  </div>
  <div class="field">

    <%= f.label :parent_id, "Parent Page(If Any):" %>

    <!-- calling form helper method and awesome_nested_set helper method to render dropdown box -->
    <%= f.select(:parent_id, nested_set_options(Page, @page) {|p|  p.title }, {:include_blank => 'Select Page'}) %>

  </div>
  <div class="field">

    <%= f.label :link_url, "Forward this page to another website or page: " %>
    <%= f.text_field :link_url, :title => "Use full url, e.g.- http://www.google.com" %>

  </div>
  <div class="field">

    <%= f.check_box :show_in_menu %>
    <%= f.label :show_in_menu %>

  </div>
  <div class="field">

    <%= f.check_box :published %>
    <%= f.label :published, "Publish this page" %>

  </div>
  <div class="actions">

    <%= f.submit %>
    <%= f.submit :value => "Preview", :id => "preview-submit" %>

  </div>

  <!-- include _form.js.erb to handle the click event on preview button -->
  <%=  render 'mcms_pages/admin/pages/form.js'%>

<% end %>

app/views/mcms_pages/admin/pages/_form.js.erb
<!--

  @File Name                 : pages/_form.js.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-19
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To show the page preview on click of preview submit button.

-->

<script type="text/javascript">

  $(document).ready(function(){

    // on click of preview button
    $("#preview-submit").live('click', function(e) {

      // Assigning the form elt in a variable
      var formElt = $(this).parents('form');

      // Assigning the form action in a variable
      var formAction = formElt.attr('action');

      // Assigning the form target in a variable
      var formTarget = formElt.attr('target');

      // setting the new action and target for form element
      formElt.attr({

        'action': '<%= @page.persisted? ? preview_page_path(@page.nested_url) : preview_pages_path %>',
        'target': '_blank'

      });

      //submit the form
      formElt.submit();

      // reset the action for form element
      formElt.attr({

        'action': formAction,
        'target': ""

      });

      //prevent the defaault action for the click event
      e.preventDefault();

    });

  });

</script>

app/views/mcms_pages/admin/pages/_page.html.erb
<!--

  @File Name                 : admin/pages/_page.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-09
  @Date Modified             : 2012-06-14
  @Last Modification Details : 'mcms-' removed from css selectors
  @Purpose                   : To display the page title and actions for all pages

-->

<li id="<%= dom_id(page) -%>" class="pages-clearfix page-records">

  <div class="pages-clearfix">

    <!-- check if pages have children -->
    <% if page.children.present? %>

      <span class="page-icon page-toggle page-expanded" title=""></span>

    <% else %>

      <span class="page-icon"></span>

    <% end %>

    <span class="page-title" >

      <%= page.title %>

    </span>
    <span class="page-actions">

      <!-- check if page is deletable -->
      <%  if deleteable?(page) %>

        <%= link_to image_tag("mcms_pages/icons/delete.png", :title => "delete this page", :alt => "delete"), admin_page_path(page),
                              :data => {:confirm => 'Are you sure?'}, method: :delete  %>

      <% end %>

      <%= link_to image_tag("mcms_pages/icons/page_edit.png", :title => "edit this page", :alt => "edit page"),
                            edit_admin_page_path(page.nested_url) %>
      <%= link_to image_tag("mcms_pages/icons/page_add.png", :title => "add a child page", :alt => "add a child"),
                             new_admin_page_path(:parent_id => page.id) %>
      <%= link_to image_tag("mcms_pages/icons/application_go.png", :title => "preview this page", :alt => "preview this page"),
                             preview_page_path(page.nested_url), :target => "_blank" %>

    </span>

  </div>


  <ul class="page-nested" data-ajax-content="<%= admin_path(page) %>">

    <!-- render partial _page.html.erb if pages have children -->
    <%= render(:partial => 'mcms_pages/admin/pages/page', :collection => page.children) if page.children.present? %>

  </ul>

</li>

app/views/mcms_pages/admin/pages/_page_part_edit_form.html.erb
<!--

  @File Name                 : admin/pages/_page_part_form.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-07-03
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To display the partial for page part edit form fields.

-->

<!-- calling helper method to arrange page part of a page -->
<% page = arrange_page_part(@page) %>

<div id='page-tabs' class="page-tabs clearfix ui-tabs ui-widget ui-widget-content ui-corner-all" >

  <ul id='page-parts-ul' class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all" >

    <!-- creating an empty array -->
    <% title = [] %>

    <!-- creating an empty hash to store page fragments value -->
    <% page_fragment = Hash.new %>

    <!--
      looping through the  array
      to display the link for different page parts
    -->
    <% @parts.each_with_index do |part, index| %>

      <li class="page-parts-li ui-state-default ui-corner-top ui-state-active " >

        <%= link_to part, "javascript:void(0)", :id => "#page-part-fields-#{index}" %>
        <% title[index] = part %>

        <!-- calling helper method to check existence of similar page parts -->
        <%  page_fragment[index] = get_fragments(part) %>

      </li>

    <% end  %>

  </ul>

  <div id='page-part-form'>

    <!-- initializing the variable to create a unique id for different page part fields -->
    <% index = 0  %>

    <!-- rendering the form for association page part -->
    <%= f.fields_for :page_parts do |p| %>

      <!-- check  if page_fragment is nil or empty -->
      <% if page[title[index]].pages.first.title == @page.title  %>

        <!-- if yes then render the partial for page_part -->
        <%= render 'mcms_pages/admin/pages/page_part_form_field',
                    :f => p,
                    :part_index => index,
                    :title => title[index]
        %>

        <%= p.hidden_field :id , :value => "#{page[title[index]].id}" unless index.nil? %>

        <!-- increment index by 1 -->
        <% index += 1 %>

      <% else %>

        <%= p.hidden_field :id , :value => "#{page[title[index]].id}" unless index.nil? %>

        <!-- increment index by 1 -->
        <% index += 1 %>

      <% end %>

    <% end %>

    <!-- initializing the variable to loop though the HASH page_fragment -->
    <% loop_index = 0 %>

    <!-- rendering the form for association page_part_pages -->
    <%= f.fields_for :page_parts_pages do |p| %>

      <% if not page[title[loop_index]].pages.first.title == @page.title %>

        <%= render 'mcms_pages/admin/pages/page_part_page_form_field',
                    :f => p,
                    :part_index => loop_index,
                    :fragment => page_fragment[loop_index],
                    :title => title[loop_index]
        %>

        <%= p.hidden_field :id , 
                     :value => "#{page[title[loop_index]].page_parts_pages.where(:page_id => @page.id).first.id}" unless loop_index.nil?
        %>

        <!-- increment loop_index by 1 -->
        <% loop_index += 1 %>

      <% else %>

        <%= p.hidden_field :id , 
                     :value => "#{page[title[loop_index]].page_parts_pages.where(:page_id => @page.id).first.id}" unless loop_index.nil?
        %>

        <!-- increment loop_index by 1 -->
        <% loop_index += 1 %>

      <% end %>

    <% end %>

  </div>

</div>

app/views/mcms_pages/admin/pages/_page_part_form.html.erb
<!--

  @File Name                 : admin/pages/_page_part_form.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-07
  @Date Modified             : 2012-06-14
  @Last Modification Details : 'mcms-' removed from css selectors
  @Purpose                   : To display the partial for page part form fields.

-->

<div id='page-tabs' class="page-tabs clearfix ui-tabs ui-widget ui-widget-content ui-corner-all" >


  <ul id='page-parts-ul' class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">

    <!-- creating an empty array -->
    <% title = [] %>

    <!-- creating an empty hash to store page fragments value -->
    <% page_fragment = Hash.new %>

    <!-- creating an empty hash to store page_parts value -->
    <% x = Hash.new %>

    <!-- creating an empty hash to store page_parts_pages value -->
    <% y = Hash.new %>

    <!-- declaring some local variables to be used as hash index in loop -->
    <% i = 0 %>
    <% j = 0 %>

    <!--
      looping through the  array
      to display the link for different page parts
    -->
    <% @parts.each_with_index do |part, index| %>

      <li class="page-parts-li ui-state-default ui-corner-top ui-state-active ">

        <%= link_to part, "javascript:void(0)", :id => "#page-part-fields-#{index}" %>
        <% title[index] = part %>

        <!-- calling helper method to check existence of similar page parts -->
        <%  page_fragment[index] = get_fragments(part) %>

        <!-- check  if page_fragment is nil or empty -->
        <% if page_fragment[index].nil? or page_fragment[index].empty? %>

          <!-- store page_parts value -->
          <% x[i] = index %>

          <!-- increment local variables by 1 -->
          <% i = i+1 %>

        <% else %>

          <!-- store page_parts_pages value -->
          <% y[j] = index %>

          <!-- increment local variables by 1 -->
          <% j = j+1 %>

        <% end %>

      </li>

    <% end  %>

  </ul>

  <div id='page-part-form'>

    <!-- initializing the variable to create a unique id for different page part fields -->
    <% index = 0  %>

    <!-- rendering the form for association page part -->
    <%= f.fields_for :page_parts do |p| %>

      <!-- check  if page_fragment is nil or empty -->
      <% if not x[index].nil? and (page_fragment[x[index]].nil? or page_fragment[x[index]].empty?) %>

        <!-- if yes then render the partial for page_part -->
        <%= render 'mcms_pages/admin/pages/page_part_form_field',
                    :f => p,
                    :part_index => x[index],
                    :title => title[x[index]]
        %>

        <!-- increment index by 1 -->
        <% index += 1 %>

      <% else %>

        <!-- increment index by 1 -->
        <% index += 1 %>

      <% end %>

    <% end %>

    <!-- initializing the variable to loop though the HASH page_fragment -->
    <% loop_index = 0 %>

    <!-- rendering the form for association page_part_pages -->
    <%= f.fields_for :page_parts_pages do |p| %>

      <% if not y[loop_index].nil? and not (page_fragment[y[loop_index]].nil? and page_fragment[y[loop_index]].empty?) %>

        <%= render 'mcms_pages/admin/pages/page_part_page_form_field',
                    :f => p,
                    :part_index => y[loop_index],
                    :fragment => page_fragment[y[loop_index]],
                    :title => title[y[loop_index]]
        %>

        <!-- increment loop_index by 1 -->
        <% loop_index += 1 %>

      <% else %>

        <!-- increment loop_index by 1 -->
        <% loop_index += 1 %>

      <% end %>

    <% end %>

  </div>

</div>

app/views/mcms_pages/admin/pages/_page_part_form_field.html.erb
<!--

  @File Name                 : admin/pages/_page_part_form_field.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-07
  @Date Modified             : 2012-06-14
  @Last Modification Details : 'mcms-' removed from css selectors
  @Purpose                   : To display page part form fields.

-->

<% page = arrange_page_part(@page) unless @page.nil? %>

<div id="page-part-fields-<%= part_index %>" class='page-part-fields'>

    <%= f.hidden_field :title, :value => "#{title}", :name => "page[page_parts_attributes][#{part_index}][title]" %>

    <%= f.hidden_field :id,
                       :name => "page[page_parts_attributes][#{part_index}][id]" unless controller.action_name != "add_page_part" %>

    <% if @page.nil? %>

      <%= f.cktext_area :body,
                        :input_html => {:name => "page[page_parts_attributes][#{part_index}][body]",
                                        :id => "page_page_parts_attributes_#{part_index}_body"},
                        :toolbar => 'Full', :width => 900, :height => 400 %>

    <% else %>

      <%= f.cktext_area :body,
                        :input_html => { :value => "#{page[title].body}", :name => "page[page_parts_attributes][#{part_index}][body]",
                                         :id => "page_page_parts_attributes_#{part_index}_body"},
                        :toolbar => 'Full', :width => 900, :height => 400
      %>

    <% end %>

    <% unless title == "main body" %>

      OR

      <%= link_to "Choose Existing #{title}",
                {:controller=>"pages", :action => 'add_page_part', :title => "#{title}", :index => "#{part_index}"},
                :remote => true, :id => "create-page-part-page-link-#{part_index}", :class => "create-page-part-page-link"
      %>

    <% end %>

</div>

app/views/mcms_pages/admin/pages/_page_part_page_form_field.html.erb
<!--

  @File Name                 : admin/pages/_page_part_page_form_field.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-26
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To display page_part_pages form fields.

-->

<div id="page-part-fields-<%= part_index %>" class='page-part-fields'>

  <%= f.label :page_part_id, "Choose Existing #{title}",
              :id => "page_page_parts_pages_attributes_#{part_index}_page_part_id" %>

  <%= f.select(:page_part_id, fragment.collect {|p| [ "#{p[1]} #{title}", p[0] ] },{},
              {:id => "page_page_parts_pages_attributes_#{part_index}_page_part_id",
              :name => "page[page_parts_pages_attributes][#{part_index}][page_part_id]"}) unless fragment.nil? %>
  OR

  <%= link_to "Create New #{title}",
              {:controller=>"pages", :action => 'add_page_part',
               :title => "#{title}", :index => "#{part_index}", :part => "page_part"},
              :remote => true,:id => "create-page-part-link-#{part_index}", :class => "create-page-part-link" %>

</div>

app/views/mcms_pages/admin/pages/add_page_part.js.erb
/*

 * @File Name                 : pages/_add_page_part.js.erb
 * @Company Name              : Mindfire Solutions Private Limited
 * @Creator Name              : Vikram Kumar Mishra
 * @Date Created              : 2012-07-03
 * @Date Modified             :
 * @Last Modification Details :
 * @Purpose                   : To show the partial for creating a page part

*/

$(document).ready(function(){

  <% if @part == "page_part" %>

    <%
        #calling helper method to create form object
        builder = build_page_part(@index)
    %>

    // remove html element with given id
    $("#page_page_parts_pages_attributes_<%= @index %>__destroy").remove();

    // insert a hidden field for destroying the page part page with default value 1.
    $("#page-part-fields-<%= @index %>").after('<%= hidden_field_tag "page[page_parts_pages_attributes][#{@index}][_destroy]", "1" %>');

    var html = "<%= escape_javascript(render 'mcms_pages/admin/pages/page_part_form_field',
                                      :part_index => @index, :f => builder, :title => @title)  %>";

  <% else %>

    <%
      #calling helper method to create form object
      builder = build_page_part_page(@index)
    %>

    <% fragment = get_fragments(@title) %>

    var html = "<%= escape_javascript(render 'mcms_pages/admin/pages/page_part_page_form_field',
                                      :part_index => @index, :f => builder, :title => @title, :fragment => fragment)  %>";

    // reset the value in hidden field for destroying page part pages to 0.
    $("#page_page_parts_pages_attributes_<%= @index %>__destroy").val("0");

  <% end %>

  // change the html content of div page-part-fields
  $("#page-part-fields-<%= @index %>").html(html);

}); // end ready function

app/views/mcms_pages/admin/pages/edit.html.erb
<!--

  @File Name                 : admin/pages/edit.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-09
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To display the partial for page form fields with pre-existing values.

-->

<!-- render partial form.html.erb -->
<%= render 'mcms_pages/admin/pages/form' %>

<!-- render partial _head.html.erb to include JS and CSS for specific page-->
<%= render :partial => "mcms_pages/layouts/head" %>

app/views/mcms_pages/admin/pages/find_child.html.erb
<!--

  @File Name                 : admin/pages/find_child.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-12
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To display the partial for page form fields with pre-existing values.

-->

<!-- render partial _page.html.erb -->
<%= render :partial => 'mcms_pages/admin/pages/page', :collection => @page.children %>

app/views/mcms_pages/admin/pages/index.html.erb
<!--
  @File Name                 : admin/pages/index.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-09
  @Date Modified             : 2012-06-14
  @Last Modification Details : 'mcms-' removed from css selectors
  @Purpose                   : To display the list of pages and actions to be taken on those pages through rendering partials.

-->

<p class="notice"> <%= notice %></p>
<div id='pages-records' class='pages-tree'>

  <ul id='page-sortable-list'>

    <!-- render partial _page.html.erb -->
    <%= render :partial => 'mcms_pages/admin/pages/page', :collection => @pages.select{|p| p.parent_id.nil?}  %>

  </ul>

</div>

<!-- render partial _action.html.erb -->
<%= render 'mcms_pages/admin/pages/action' %>

<!-- render partial _head.html.erb to include JS and CSS for specific page-->
<%= render :partial => "mcms_pages/layouts/head" %>

app/views/mcms_pages/admin/pages/new.html.erb
<!--

  @File Name                 : admin/pages/new.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-09
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To display the partial for page form fields.

-->

<!-- render partial form.html.erb -->
<%= render 'mcms_pages/admin/pages/form'  %>

<!-- render partial _head.html.erb to include JS and CSS for specific page-->
<%= render :partial => "mcms_pages/layouts/head" %>