config/routes.rb
=begin

  @File Name                 : routes.rb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-05
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To redirect the pages throughout the application.

=end

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  #resources :pages

  # defining root path for the application
  #root :to => "pages#home"

  # post to page preview action
  post 'pages/preview'     => 'pages#preview', :as => :preview_pages

  match 'pages/blog/preview' => redirect("/blog/posts") if Gem.available?("mcms_blog")

  # match pages/**/preview to action preview of pages controller
  match 'pages/*path/preview' => 'pages#preview', :as => :preview_page,  :via => [:get, :put]

  # define route for namespace admin for different resources to have
  # path prefixed with "mcms"
  namespace :admin, :path => "mcms" do

    # matching pages/page_title OR id/find_child will be redirected to
    # find_child action for pages controller within namespace admin
    match 'pages/*path/find_child', :to => 'pages#find_child'

    # get edit path for parent and child(url prepended with parent) page both
    # and redirect to edit action
    get 'pages/*path/edit', :to => 'pages#edit'

    resources :layouts do

      collection do

        get 'find_and_use_layout'

      end

    end

    resources :pages do

      collection do

        get 'add_page_part'

      end

    end

  end # end namespace

  match '/:path' => "pages#show"

  match '*path', :to=> 'pages#show', :as => :show_page unless Gem.available?("mcms")

end

app/views/mcms_pages/pages/_main_body.html.erb
<!--
  @File Name                 : _main_body.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-14
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To display the main body content of pages.

-->

<div class="page-<%= side %>-body" id="<%= layout %>-<%= side %>-body">

  <%  if p.nil? %>

    <p style="color:red;font-weight:bold;">Please Create the body of the Page, You have not created it yet.</p>

  <% else %>

    <%= p.body.html_safe  %>

  <% end %>

</div>

app/views/mcms_pages/pages/_menu.html.erb
<!--
  @File Name                 : pages/_menubar.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-07-05
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To show the menu items.

-->

<div class="pages-menu" id="pages-menu">

  <ul class="pages-menu-ul">

    <!-- include menubar page for the application-->
    <%= 
      render :partial => 'mcms_pages/pages/menubar', :collection => @menu_pages.select{|p| p.parent_id.nil? and p.link_url != '/404'}
    %>

  </ul>

</div>

app/views/mcms_pages/pages/_menubar.html.erb
<!--
  @File Name                 : pages/_menubar.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-07-05
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To show the menu items.

-->

<li id="<%= dom_id(menubar) -%>" class="pages-menu-li">

  <% if controller.action_name == "preview" %>

    <%= link_to menubar.title, preview_page_path(menubar.nested_url) %>

  <% else %>

    <%= link_to menubar.title, show_page_path(menubar.nested_url) %>

  <% end %>

  <% if menubar.children.present? and menubar.link_url != "/" %>

    <ul class="pages-nested-menu-ul">

      <!-- render partial _menubar.html.erb if pages have children -->
      <%=
        render(:partial => 'mcms_pages/pages/menubar', :collection => menubar.children.select{|p| p.show_in_menu? and p.published?})
      %>

    </ul>

  <% end %>

</li>

app/views/mcms_pages/pages/show.html.erb
<!--
  @File Name                 : pages/show.html.erb
  @Company Name              : Mindfire Solutions Private Limited
  @Creator Name              : Vikram Kumar Mishra
  @Date Created              : 2012-06-05
  @Date Modified             : 2012-06-14
  @Last Modification Details :
  @Purpose                   : To show the individual page preview, on the basis of layout choosed.

-->

<% page = arrange_page_part(@page) %>

<!-- render partial for header -->
<%= render :partial => 'mcms_pages/layouts/header', :locals => {:p => page["header"]} unless page["header"].nil? %>

<!-- render menu page -->
<%= render :partial => 'mcms_pages/pages/menu' if not @page.link_url == '\404' %>

<!-- render partial _main_body.html.erb -->
<%=
  render "mcms_pages/pages/main_body", :p => page["left body"], :side => "left", :layout => layout_name(@page.layout.column_count) unless page["left body"].nil?
%>

<!-- render partial _main_body.html.erb -->
<%=
  render "mcms_pages/pages/main_body", :p => page["right body"], :side => "right", :layout => layout_name(@page.layout.column_count) unless page["right body"].nil?
%>

<!-- render partial _main_body.html.erb -->
<%=
  render "mcms_pages/pages/main_body", :p => page["main body"], :side => "main", :layout => layout_name(@page.layout.column_count) unless page["main body"].nil?
%>

<!-- render partial for footer -->
<%= render :partial => 'mcms_pages/layouts/footer', :locals => {:p => page["footer"]}  unless page["footer"].nil?  %>